// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Agenda
{
    public int IdAgenda { get; set; }

    public string Titulo { get; set; }

    public string Descricao { get; set; }

    public DateTime? DataInicio { get; set; }

    public DateTime? DataFim { get; set; }

    public string Localidade { get; set; }

    public string Responsavel { get; set; }

    public byte[] Visibilidade { get; set; }
}