// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace ChurchManagement.Core.Entidades;

public partial class Cargo
{
    public Cargo(int idDepartamento, string nome, string descricao, string funcao, int ativo)
    {
        IdDepartamento = idDepartamento;
        Nome = nome;
        Descricao = descricao;
        Funcao = funcao;
        Ativo = ativo;
    }
    public int IdCargo { get; private set; }
    public int IdDepartamento { get; private set; }
    public string Nome { get; private set; }
    public string Descricao { get; private set; }
    public string Funcao { get; private set; }
    public int Ativo { get; private set; }

    public void Update(int idDepartamento, string nome, string descricao, string funcao, int ativo)
    {
        IdDepartamento = idDepartamento;
        Nome = nome;
        Descricao = descricao;
        Funcao = funcao;
        Ativo = ativo;
    }
}