// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace ChurchManagement.Core.Entidades;

public partial class Cargo
{
    public int IdCargo { get; set; }

    public int IdDepartamento { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public string Funcao { get; set; }

    public byte[] Ativo { get; set; }
}