// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace ChurchManagement.Core.Entidades;

public partial class CategoriaDespesa
{
    public CategoriaDespesa(string nome)
    { 
        Nome = nome;
    }
    public int IdCategoria { get; private set; }
    public string Nome { get; private set; }
    public void Update(int idCategoria, string nome)
    {
        Nome = nome;
        IdCategoria = idCategoria;
    }
}