// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Departamento
{
    public int IdDepartamento { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }

    public string Lider { get; set; }
}