// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Departamento
{
    public Departamento(string nome, string descricao, string lider)
    {
        Nome = nome;
        Descricao = descricao;
        Lider = lider;
    }
    public int IdDepartamento { get; private set; }
    public string Nome { get; private set; }
    public string Descricao { get; private set; }
    public string Lider { get; private set; }

    public void Update(string nome, string descricao, string lider)
    {
        Nome = nome;
        Descricao = descricao;
        Lider = lider;
    }

}