// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Despesa
{

    public Despesa(int idCategoria, DateTime? dataDespesa, string descricao, decimal? valor, byte[] reciboPagamento)
    {
        IdCategoria = idCategoria;
        DataDespesa = dataDespesa;
        Descricao = descricao;
        Valor = valor;
        ReciboPagamento = reciboPagamento;
    }

    public int IdDespesas { get; private set; }
    public int IdCategoria { get; private set; }
    public DateTime? DataDespesa { get; private set; }
    public string Descricao { get; private set; }
    public decimal? Valor { get; private set; }
    public byte[] ReciboPagamento { get; private set; }
}