// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Despesa
{
    public int IdDespesas { get; set; }

    public int IdCategoria { get; set; }

    public DateTime? DataDespesa { get; set; }

    public string Descricao { get; set; }

    public decimal? Valor { get; set; }

    public byte[] ReciboPagamento { get; set; }
}