// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ChurchManagement.Core.Enums;

namespace ChurchManagement.Core.Entidades;

public partial class Membro
{
    public Membro(int idCargo, string nomeCompleto,
        DateTime? dataNasc,
        byte[] imagemMembro, CargoEnum cargo,
        EstadoCivilEnum estadoCivil, string endereco,
        string telefone, string email, DateTime? dataBatismo)
    {
        IdCargo = idCargo;
        NomeCompleto = nomeCompleto;
        DataNasc = dataNasc;
        ImagemMembro = imagemMembro;
        Cargo = cargo;
        EstadoCivil = estadoCivil;
        Endereco = endereco;
        Telefone = telefone;
        Email = email;
        DataCadastro = DateTime.UtcNow;
        DataBatismo = dataBatismo;
    }
    public int IdMembro { get; private set; }
    public int IdCargo { get; private set; }
    public string NomeCompleto { get; private set; }
    public DateTime? DataNasc { get; private set; }
    public byte[] ImagemMembro { get; private set; }
    public CargoEnum Cargo { get; private set; }
    public EstadoCivilEnum EstadoCivil { get; private set; }
    public string Endereco { get; private set; }
    public string Telefone { get; private set; }
    public string Email { get; private set; }
    public DateTime? DataCadastro { get; private set; }
    public DateTime? DataBatismo { get; private set; }

    public void UpdateMembro(int idCargo, string nomeCompleto,
        DateTime? dataNasc,
        byte[] imagemMembro, CargoEnum cargo,
        EstadoCivilEnum estadoCivil, string endereco,
        string telefone, string email, DateTime? dataBatismo)
    {
        IdCargo = idCargo;
        NomeCompleto = nomeCompleto;
        DataNasc = dataNasc;
        ImagemMembro = imagemMembro;
        Cargo = cargo;
        EstadoCivil = estadoCivil;
        Endereco = endereco;
        Telefone = telefone;
        Email = email;
        DataCadastro = DateTime.UtcNow;
        DataBatismo = dataBatismo;
    }
}