// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class MembroDepartamento
{
    public int IdMembro { get; set; }

    public int IdDepartamento { get; set; }
}