// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class ObjetivosFinanceiro
{
    public int IdObjetivo { get; set; }

    public decimal? QuantidadeAlvo { get; set; }

    public string Titulo { get; set; }

    public int? StatusObjetivo { get; set; }

    public DateTime? CriadoEm { get; set; }
}