// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ChurchManagement.Core.Enums;
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class ObjetivosFinanceiro
{
    public ObjetivosFinanceiro(decimal? quantidadeAlvo, string titulo, StatusObjetivoEnum statusObjetivo)
    {
        QuantidadeAlvo = quantidadeAlvo;
        Titulo = titulo;
        StatusObjetivo = statusObjetivo;
        CriadoEm = DateTime.Now;
    }

    public int IdObjetivo { get; private set; }
    public decimal? QuantidadeAlvo { get; private set; }
    public string Titulo { get; private set; }
    public StatusObjetivoEnum StatusObjetivo { get; private set; }
    public DateTime? CriadoEm { get; private set; }
}