// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Post
{
    public Post(string titulo, string assunto)
    {
        Titulo = titulo;
        Assunto = assunto;
    }
    public int IdPost { get; private set; }
    public string Titulo { get; private set; }
    public string Assunto { get; private set; }
    public byte[] Imagem { get; set; }

    public void Update(string titulo, string assunto)
    {
        Titulo = titulo;
        Assunto = assunto;
    }
}