// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Post
{
    public int IdPost { get; set; }

    public string Titulo { get; set; }

    public string Assunto { get; set; }

    public byte[] Imagem { get; set; }
}