// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class Tesouraria
{
    public int IdTesouraria { get; set; }

    public int? TipoEntrada { get; set; }

    public decimal? Quantidade { get; set; }

    public DateTime? DataEntrada { get; set; }

    public DateTime? DataSaida { get; set; }

    public int? TipoSaida { get; set; }
}