// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ChurchManagement.Core.Enums;
using System;
using System.Collections.Generic;

namespace ChurchManagement.Core.Entidades;

public partial class TransacaoTesouraria
{
    public TransacaoTesouraria(TipoTransacaoEnum tipoTransacao, EntradaEnum tipoEntrada, decimal? quantidade, string descricao, int idTesouraria)
    {
        TipoTransacao = tipoTransacao;
        TipoEntrada = tipoEntrada;
        Quantidade = quantidade;
        Descricao = descricao;
        IdTesouraria = idTesouraria;
        DataTransacao = DateTime.Now;
    }

    public TransacaoTesouraria(int idTesouraria, TipoTransacaoEnum tipoTransacao, decimal? quantidade,
        string descricao, TipoSaidaEnum? tipoSaida)
    {
        TipoTransacao = tipoTransacao;
        TipoSaida = tipoSaida;
        Quantidade = quantidade;
        Descricao = descricao;
        IdTesouraria = idTesouraria;

        DataTransacao = DateTime.Now;
    }

    public int IdTesourariaTransacao { get; set; }
    public int IdTesouraria { get; set; }
    public TipoTransacaoEnum TipoTransacao { get; set; }
    public decimal? Quantidade { get; set; }
    public DateTime? DataTransacao { get; set; }
    public string Descricao { get; set; }
    public TipoSaidaEnum? TipoSaida { get; set; }
    public EntradaEnum? TipoEntrada { get; set; }
}