// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ChurchManagement.Core.Entidades;

public partial class ChurchManagementContext : DbContext
{
    public ChurchManagementContext(DbContextOptions<ChurchManagementContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agenda> Agenda { get; set; }

    public virtual DbSet<Cargo> Cargos { get; set; }

    public virtual DbSet<CategoriaDespesa> CategoriaDespesas { get; set; }

    public virtual DbSet<Departamento> Departamentos { get; set; }

    public virtual DbSet<Despesa> Despesas { get; set; }

    public virtual DbSet<Membro> Membros { get; set; }

    public virtual DbSet<MembroDepartamento> MembroDepartamentos { get; set; }

    public virtual DbSet<ObjetivosFinanceiro> ObjetivosFinanceiros { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<Tesouraria> Tesouraria { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agenda>(entity =>
        {
            entity.HasKey(e => e.IdAgenda).HasName("PK__Agenda__FACC499E8B64B628");

            entity.Property(e => e.DataFim).HasPrecision(0);
            entity.Property(e => e.DataInicio).HasPrecision(0);
            entity.Property(e => e.Descricao)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Localidade)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Responsavel)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Visibilidade)
                .HasMaxLength(1)
                .IsFixedLength();
        });

        modelBuilder.Entity<Cargo>(entity =>
        {
            entity.HasKey(e => e.IdCargo).HasName("PK__Cargo__6C9856250C1F6EC2");

            entity.ToTable("Cargo");

            entity.HasIndex(e => e.IdDepartamento, "Cargo_FKIndex1");

            entity.Property(e => e.Ativo)
                .HasMaxLength(1)
                .IsFixedLength();
            entity.Property(e => e.Descricao)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Funcao)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<CategoriaDespesa>(entity =>
        {
            entity.HasKey(e => e.IdCategoria).HasName("PK__Categori__A3C02A105F5852EE");

            entity.ToTable("CategoriaDespesa");

            entity.Property(e => e.Nome)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.IdDepartamento).HasName("PK__Departam__787A433D48D31CBF");

            entity.ToTable("Departamento");

            entity.Property(e => e.Descricao)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Lider)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Despesa>(entity =>
        {
            entity.HasKey(e => e.IdDespesas).HasName("PK__Despesas__BA81E3F05DA6FF97");

            entity.HasIndex(e => e.IdCategoria, "Despesas_FKIndex1");

            entity.Property(e => e.DataDespesa).HasPrecision(0);
            entity.Property(e => e.Descricao)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ReciboPagamento).HasMaxLength(1000);
            entity.Property(e => e.Valor).HasColumnType("decimal(10, 0)");
        });

        modelBuilder.Entity<Membro>(entity =>
        {
            entity.HasKey(e => e.IdMembro).HasName("PK__tmp_ms_x__570E271F8F33D573");

            entity.ToTable("Membro");

            entity.HasIndex(e => e.IdCargo, "Membro_FKIndex1");

            entity.Property(e => e.DataBatismo).HasPrecision(0);
            entity.Property(e => e.DataCadastro).HasPrecision(0);
            entity.Property(e => e.DataNasc).HasPrecision(0);
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Endereco)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.NomeCompleto)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Telefone)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MembroDepartamento>(entity =>
        {
            entity.HasKey(e => new { e.IdMembro, e.IdDepartamento }).HasName("PK__MembroDe__9089832CC8DCFFF1");

            entity.ToTable("MembroDepartamento");

            entity.HasIndex(e => e.IdMembro, "Membro_has_Departamento_FKIndex1");

            entity.HasIndex(e => e.IdDepartamento, "Membro_has_Departamento_FKIndex2");
        });

        modelBuilder.Entity<ObjetivosFinanceiro>(entity =>
        {
            entity.HasKey(e => e.IdObjetivo).HasName("PK__Objetivo__E210F071830FA9C0");

            entity.ToTable("ObjetivosFinanceiro");

            entity.Property(e => e.CriadoEm).HasPrecision(0);
            entity.Property(e => e.QuantidadeAlvo).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasKey(e => e.IdPost).HasName("PK__Post__F8DCBD4D22CEE002");

            entity.ToTable("Post");

            entity.Property(e => e.Assunto)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Imagem).HasMaxLength(1);
            entity.Property(e => e.Titulo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tesouraria>(entity =>
        {
            entity.HasKey(e => e.IdTesouraria).HasName("PK__Tesourar__DB4E07B5A6277839");

            entity.Property(e => e.DataEntrada).HasPrecision(0);
            entity.Property(e => e.DataSaida).HasPrecision(0);
            entity.Property(e => e.Quantidade).HasColumnType("decimal(10, 0)");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuario__5B65BF97FEB73D6A");

            entity.ToTable("Usuario");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nome)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Papel)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Senha)
                .HasMaxLength(100)
                .IsUnicode(false);
        });


        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}